### ISSUE TITLE
RateLimitError: You exceeded your current quota, please check your plan and billing details.

### ISSUE THREAD

**Issue by Doessing** [emillykkejensen/polGPT#1]
Lavede en ny OpenAI API Key, satte den ind i PolGPT og spurgte,
"I blandt MFer, Kan du finde mig top 3 IT eksperter i folketinget?"

LLM encountered an error...
RateLimitError: You exceeded your current quota, please check your plan and billing details.

![image](https://github.com/emillykkejensen/polGPT/assets/50447646/20799e07-810c-4acb-b287-eb5ce5d39073)
[error details.txt](https://github.com/emillykkejensen/polGPT/files/12473162/error.details.txt)

**Comment by emillykkejensen** [comment]
Hej Søren

Det er fordi du ikke har flere penge på din OpenAI konto.

[image: image.png]

Med venlig hilsen

---------------------------------------------------

Emil Lykke Jensen

E: ***@***.***
C: +45 2585 1619 <25%2085%2016%2019>
T: twitter.com/emillykkejensen <http://www.twitter.com/emillykkejensen>
L: dk.linkedin.com/in/emillykkejensen



Den ons. 30. aug. 2023 kl. 09.57 skrev Søren Døssing <
***@***.***>:
